"""Generate docs/data_refresh_guide.docx - the fillable annual update guide.

Answers what future-you needs to know once a year: for each input file, where it
comes from, who to ask, and how to get the new version - plus a checklist for the
update itself and how scripts/check_data_sources.py fits in.

Reuses the layout helpers from generate_role_questions_docx.py so this looks and
behaves like the round-1/round-2 question sheets (bordered ANSWER boxes, mono
literal names).

    python scripts/generate_data_refresh_guide_docx.py
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from docx.shared import Inches, Pt

from generate_role_questions_docx import (  # noqa: E402
    ACCENT, INK_SOFT, Document, _answer_box, _bullet, _heading, _para, _question, _table,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "docs" / "data_refresh_guide.docx"

SOURCE_PROMPT = (
    "Source system / who maintains it — How you get the new year's file — "
    "Who to contact if something looks wrong — Roughly when in the year it's ready:"
)


def _source_file(doc, filename: str, used_for: str, format_notes: list, fragility: str = "") -> None:
    _heading(doc, filename, 3)
    _para(doc, f"Used for: {used_for}")
    for note in format_notes:
        _bullet(doc, note)
    if fragility:
        _para(doc, f"Fragility: {fragility}", color=INK_SOFT, italic=True)
    _answer_box(doc, SOURCE_PROMPT, lines=4)


def build() -> Document:
    doc = Document()

    props = doc.core_properties
    props.title = "Annual Data Refresh Guide"
    props.subject = "Where each input file comes from, who to ask, and how to check the format hasn't drifted"
    props.author = "Computer Science Workload Model"
    props.comments = ("Generated by scripts/generate_data_refresh_guide_docx.py. "
                      "Re-running overwrites this file - copy a partly-answered "
                      "version before regenerating.")

    normal = doc.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(10.5)
    normal.paragraph_format.space_after = Pt(6)

    for section in doc.sections:
        section.left_margin = Inches(0.9)
        section.right_margin = Inches(0.9)
        section.top_margin = Inches(0.8)
        section.bottom_margin = Inches(0.8)

    # ---- masthead -------------------------------------------------------
    _heading(doc, "Annual Data Refresh Guide", 1)
    _para(doc,
          "The model runs on 10 files in data/, refreshed once a year. This is the "
          "reference for doing that refresh: where each file comes from, who to ask, "
          "and what to check hasn't silently changed shape. Fill in the ANSWER boxes "
          "once and this becomes next year's instructions, not a re-investigation.",
          color=INK_SOFT)

    # ---- the process ------------------------------------------------------
    _heading(doc, "The annual process", 2)
    _para(doc, "A draft checklist - amend to match how you'd actually want to run this:")
    for step in [
        "Obtain the new academic year's version of each file below (see each file's "
        "entry for where it comes from) and drop it into data/, replacing last "
        "year's copy under the same filename.",
        "Run `python scripts/check_data_sources.py` before anything else. It checks "
        "every file's column headers (or, for the two files with no header row, "
        "the raw layout) against what's recorded from a known-good year, and flags "
        "anything that's moved, been renamed, or disappeared - the exact kind of "
        "change that would otherwise produce wrong numbers with no error. Resolve "
        "any FAIL before continuing; read through the WARNs.",
        "Run `python main.py --dry-run` to load everything without calculating, and "
        "check the data summary and any \"Data warning\" lines look sane for the new "
        "year (right module count, right staff count, no unexpected zeros).",
        "Update `data/staff_name_lookup.json` for anyone new, departed, or renamed, "
        "and `data/module_mapping.json` for any module renamed, merged, or dropped "
        "between years. `main.py --interactive` will prompt for unrecognised names "
        "as you go rather than requiring this be done up front.",
        "Run `python main.py` for the full calculation and read through the printed "
        "\"Data warning\"/\"[ERROR]\" lines - each names the module or person it's "
        "about.",
        "Spot-check a handful of individual reports against last year's for rough "
        "plausibility (nobody who was full-time last year should show as 0.2 FTE "
        "this year, etc.) before treating the run as authoritative.",
        "If the changes are intentional, regenerate the baseline "
        "(`scripts/generate_baseline.py`) so the test suite tracks the new numbers "
        "rather than flagging them as drift.",
    ]:
        _bullet(doc, step)
    _answer_box(doc, "Corrections to the checklist above - steps to add, remove, or reorder:", lines=4)

    _heading(doc, "What check_data_sources.py actually catches", 2)
    _para(doc,
          "Every loader in data_loader.py reads columns either by header name or by "
          "raw position. Neither fails loudly when a source file's shape changes - a "
          "renamed column just makes that field read as empty/zero for every row, "
          "silently, for the rest of the run. This script is a header/shape check "
          "against the format recorded on 2026-08-18, run before the real load:")
    for item in [
        "The 7 files read by column name (CS Module Numbers, CS Module Assessment "
        "Numbers, pastoral_load, Loadings, PhD Supervision, % FTE for CS, Part "
        "time): flags any column the loader depends on that's gone missing, and "
        "any genuinely new column, so a restructure gets noticed either way.",
        "Part time.csv specifically: it has two columns both literally named "
        "\"FTE\" in the source sheet. Python's DictReader silently keeps only the "
        "second one - today that happens to be the real fraction (confirmed "
        "2026-08-18), but nothing would catch it if the two columns were ever "
        "swapped. The checker flags this every run as a standing reminder to verify.",
        "The WTW workbook: confirms the current and previous year's sheets both "
        "carry the columns the loader depends on. Read by column name since the "
        "2026-08-18 migration, so a reordered column is handled correctly - this "
        "check mainly catches a genuinely renamed or removed column.",
        "WAW.csv, which has no header row: confirms the section markers "
        "(\"On-Campus\", \"Research Roles\", etc.) that _load_waw_roles() "
        "structurally relies on are still present.",
        "The ART Performance sheet: flags any contract-category value other than "
        "\"ART\"/\"T&S\" - the loader silently excludes anyone tagged with an "
        "unrecognised category, which is exactly how Philippa Ryan and Kate P "
        "were found to have no contract category (2026-08-18).",
    ]:
        _bullet(doc, item)
    _para(doc,
          "It can't catch everything - a column that keeps its name but changes "
          "meaning (hours instead of a percentage, say) passes silently. Treat a "
          "clean run as \"the shape looks right,\" not \"the values are right.\"",
          color=INK_SOFT, italic=True)

    doc.add_page_break()

    # ---- per-file entries -------------------------------------------------
    _heading(doc, "The 10 source files", 2)
    _para(doc,
          "In the order the pipeline loads them. \"Used for\" and the format notes "
          "are pre-filled from the code as of 2026-08-18 - correct them if they're "
          "wrong rather than just filling the blank below.",
          color=INK_SOFT)

    _source_file(
        doc, "CS WTW Who Teaches What.xlsx",
        "Module list: name, codes, stage, semester, credits, cohort, lead, teachers, "
        "checkers, practicals count - one sheet per academic year, named e.g. "
        "\"2026-7\". Migrated 2026-08-18 from two CSVs (WTW 2026-7.csv / "
        "WTW 2025-6.csv) after confirming this workbook carries equivalent - and, "
        "for the current year, more up to date - information. The previous-year "
        "sheet is used only to detect who taught a module last year, for the "
        "new-lecturer multiplier; none of its student/assessment numbers are used.",
        [
            "load_wtw_files()/load_previous_wtw() auto-pick the latest two "
            "sheets matching a \"YYYY-Y\" name pattern as current/previous year - "
            "adding next year just means adding a new sheet with that name, no "
            "code change needed.",
            "Columns are read by NAME (not position, since the 2026-08-18 "
            "migration) - a reordered column is handled correctly rather than "
            "silently misread. A genuinely renamed/missing column still reads "
            "as blank for that field; scripts/check_data_sources.py catches this.",
            "\"SC\" in the Stage column marks the block-taught SCSE modules - "
            "confirm any newly block-taught module also gets \"SC\".",
            "SAINTS modules (cohort = \"SAINTS\") have no module code - kept via "
            "a codes-fallback (using the module name) rather than dropped, then "
            "excluded from teaching hours via module_mapping.json's "
            "excluded_modules, same mechanism as \"Projects\".",
            "The workbook's other tabs (Allocation, General Checking, and any "
            "sheet older than the two most recent years) are human planning aids "
            "with no consumer in this pipeline - safe to ignore.",
        ],
        fragility="Names typed into this workbook can carry a curly apostrophe "
                  "(’) where staff_name_lookup.json's aliases use a plain \"'\" "
                  "- normalize_name() now folds both to the same character before "
                  "matching, but a genuinely new name variant (not just a curly "
                  "quote) still needs an alias added by hand, same as always.",
    )

    _source_file(
        doc, "CS Module Numbers.csv",
        "Student headcount per module code.",
        ["Columns: Module Code, Acronym, Student Numbers.",
         "A non-numeric Student Numbers value is silently skipped - that module "
         "falls back to the 100-student default with no error, only a printed "
         "\"Data warning\"."],
    )

    _source_file(
        doc, "CS Module Assessment Numbers.csv",
        "Assessment counts, practical session counts, practical duration and "
        "week-schedule notes per module.",
        ["Columns: Module Acronym, Module Code, Number of Assessments, Number of "
         "Practicals, Total Duration, Number of Practical Groups, Notes on practicals.",
         "Practical week numbers and contact-hour duration are extracted from the "
         "free-text \"Notes on practicals\" column by pattern-matching phrases like "
         "\"Weeks 1,2,3\" and \"2 hours\" - a differently-worded note (e.g. "
         "\"wks 1-3\") would silently fail to match."],
        fragility="The only file where free-text prose, not a structured column, "
                  "carries real data the calculator depends on.",
    )

    _source_file(
        doc, "pastoral_load.csv",
        "Pastoral supervision headcount per supervisor - the preferred source "
        "(CLAUDE.md), used ahead of Loadings.csv's Pastoral Load column.",
        ["Columns: Supervisor, UG & PGT Supervisees."],
    )

    _source_file(
        doc, "Project and Pastoral Group Loads - Loadings.csv",
        "Project supervision load (sole source) plus a pastoral-load fallback for "
        "anyone missing from pastoral_load.csv. Also the only place a below-1.0 "
        "FTE note currently gets recorded for some staff (e.g. Claudio Guarnera, "
        "Mark Nicholson), even though the model reads actual FTE from Part time.csv.",
        ["~44 columns; only Person, Active, Base project load, Base pastoral load, "
         "Project Load, Pastoral Load and Notes are read.",
         "Comments in the code note this file superseded an older project_load.csv "
         "with the same columns but stale computed values - if that file still "
         "exists anywhere, it's dead and potentially misleading."],
    )

    _source_file(
        doc, "PhD Supervision Data.csv",
        "PhD supervisor / co-supervisor / assessor counts per staff member.",
        ["Columns: Staff member, Total as supervisor, Sole supervisor, "
         "Co-supervisor, TAP member, and the long combined column \"Total as "
         "supervisor (sole or co-supervisor) AND TAP member\" - if the source "
         "sheet ever reworks that header's wording, it would silently read as 0 "
         "for everyone."],
    )

    _source_file(
        doc, "% FTE for CS.csv",
        "Research grant FTE allocation, despite the filename - this is grant data, "
        "not staff FTE.",
        ["Columns: Project Lead, Project ID, Finance Project Code, Project Type, "
         "Project Title, % FTE, PI or Co-I, Project Dates Start/End (plus several "
         "unused columns).",
         "\"% FTE\" is stored as raw text (e.g. \"25%\") here - it's parsed to a "
         "number downstream in workload_calculator.py, not in the loader."],
    )

    _source_file(
        doc, "WAW.csv  (Who Administers What)",
        "Departmental role assignments - who holds each admin role, at what "
        "percentage (rates come from params/workload_parameters.yaml, not this file).",
        ["No header row at all - role/holder pairs start from line 1, organised "
         "around section-marker rows (\"On-Campus\", \"Research Roles\", etc.).",
         "A role held by more than one person needs the role name repeated on "
         "every row - a blank first cell is silently skipped (this dropped 3 of 4 "
         "Ethics Committee members until fixed, 2026-08-18).",
         "Every role name here must exactly match a key in "
         "params/workload_parameters.yaml (via the translation table in "
         "data_loader.py's _WAW_ROLE_MAPPING) - since 2026-08-18 a name that "
         "doesn't match now gets flagged in each holder's Missing Data, rather "
         "than silently costing 0 hours."],
        fragility="This is the file most likely to need a genuine structural "
                  "edit each year (new roles, retired roles, name changes) rather "
                  "than a like-for-like data swap - it's maintained by hand, not "
                  "downloaded from anywhere.",
    )

    _source_file(
        doc, "Part time.csv",
        "Staff FTE and contract category (ART / T&S). The sole source of FTE for "
        "the whole model - anyone missing from this file is treated as 1.0 FTE.",
        ["~28 columns; only Surname, Staff Category and FTE are read by the loader.",
         "The real header has \"FTE\" TWICE. DictReader keeps only the second "
         "occurrence - currently the correct one (confirmed 2026-08-18) but this "
         "is worth a manual eyeball each year, since nothing would catch the two "
         "columns being swapped.",
         "\"Notes for 25-26\" is year-stamped in the header text itself and will "
         "read as blank once the year rolls over unless the loader's default "
         "column name is updated to match - harmless (Notes is informational "
         "only) but easy to forget."],
        fragility="As of 2026-08-18 this file has only 4 rows (Carrington, "
                  "Pumfrey, Sujan, R. Wilson), none of whom were on that year's "
                  "roster - meaning FTE had silently defaulted to 1.0 for "
                  "everyone actually in the model. Confirm each year's refresh "
                  "actually covers everyone genuinely part-time, not just "
                  "whoever happened to be in last year's copy.",
    )

    _source_file(
        doc, "CS Data Collection on ART Performance ... .csv",
        "Contract category (ART / T&S) - the fallback source when Part time.csv "
        "doesn't have someone.",
        ["No header row used by the loader (plain csv.reader) - column 2 must be "
         "exactly \"T&S\" or \"ART\"; any other value silently excludes that "
         "person from category resolution.",
         "Filename is year-stamped (\"...2026 - MASTER...\") and hardcoded as the "
         "loader's default - the new year's file needs either a matching rename "
         "or a code change, not just a drop-in.",
         "Names are parsed as \"Lastname, Firstname\" - one hardcoded typo fix "
         "exists for a known misspelling (\"Soumua\" -> \"Soumya\"); a new typo in "
         "the source sheet would need the same treatment."],
    )

    doc.add_page_break()

    # ---- internal maintenance files ---------------------------------------
    _heading(doc, "Files maintained by this process, not pulled from elsewhere", 2)
    _para(doc,
          "Two more files matter every year but aren't external sources - they're "
          "hand-maintained as staff and modules change:")
    _bullet(doc, "data/staff_name_lookup.json - canonical name -> alias mapping. "
                "Grows automatically when main.py --interactive prompts for an "
                "unrecognised name; otherwise edited by hand.")
    _bullet(doc, "data/module_mapping.json - module renames, H/M merges, and "
                "dropped/new modules between academic years.")
    _answer_box(doc,
                "Anything about maintaining these two that's worth recording - "
                "e.g. how you decide a name variant is the same person, or where "
                "you'd look to confirm a module was genuinely dropped rather than "
                "just missing from this year's WTW extract:", lines=4)

    _heading(doc, "Anything else", 2)
    _answer_box(doc, "Sources, gotchas, or context not covered above:", lines=6)

    return doc


if __name__ == "__main__":
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    build().save(OUTPUT_PATH)
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
