"""Generate docs/role_reconciliation_questions_round2.docx - follow-up questions raised
by processing the answered round-1 sheet.

Reuses the layout helpers from generate_role_questions_docx so both rounds look and
behave the same (bordered ANSWER boxes, mono-rendered literal names).

    python scripts/generate_role_questions_round2_docx.py
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from docx.shared import Pt

from generate_role_questions_docx import (  # noqa: E402
    ACCENT, INK_SOFT, Document, _answer_box, _heading, _para, _question, _table,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "docs" / "role_reconciliation_questions_round2.docx"


def build() -> Document:
    doc = Document()

    props = doc.core_properties
    props.title = "Role Reconciliation — Round 2"
    props.subject = "Follow-up questions raised by the answered round-1 sheet"
    props.author = "Computer Science Workload Model"
    props.comments = ("Generated by scripts/generate_role_questions_round2_docx.py. "
                      "Re-running overwrites this file — copy a partly-answered version first.")

    normal = doc.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(10.5)
    normal.paragraph_format.space_after = Pt(6)

    from docx.shared import Inches
    for section in doc.sections:
        section.left_margin = Inches(0.9)
        section.right_margin = Inches(0.9)
        section.top_margin = Inches(0.8)
        section.bottom_margin = Inches(0.8)

    _heading(doc, "Role Reconciliation — Round 2", 1)
    _para(doc,
          "All 26 round-1 answers have been processed. Fourteen decisions are already applied "
          "and verified; seven questions remain. Two of them are new — they surfaced while "
          "implementing your answers, not from the original review.",
          color=INK_SOFT)

    _heading(doc, "Applied and verified — no action needed from you", 2)
    _table(doc,
           ["Change", "Effect"],
           [("Q0 — five role renames", "Wright & Beeston 493 h each, Liu 328 h, StAMP 66 h ×3, Yuan 164 h"),
            ("Q2 — `CSCSE SQA` → `CSCSE HAP` in WAW", "Tommy Yuan now 164.2 h for the partnership"),
            ("Q5 — Mumbai row added", "Soumya Banerjee 164.2 h"),
            ("Q6 — Group Leads block restructured", "6 rostered leads 164.2 h each; copy on your Desktop"),
            ("Q21 — FTE rows added", "Claudio 0.4 (nominal 1642 h → 656.8 h); Mark Nicholson 0.8"),
            ("Q22 — Ethics continuation rows", "Bello, Levett and Jia now credited, not dropped"),
            ("Q24 — duplicate CPD row removed", "no longer double-counts"),
            ("Q3, Q4, Q18", "no action — APVC and REF 2029 were never in the spec or code")],
           widths=[2.3, 4.3])

    _para(doc,
          "Still held pending the answers below: the six Appendix A retirements (Q8–Q14), the "
          "EDI rate (Q16), the `PGR Training Officer` rename (Q25), Module Leader (Q20), and "
          "flagging unknown role names (Q23). They are all one coherent edit to the spec and "
          "the calculator, and questions R1 and R4 change what that edit should say.",
          color=INK_SOFT, italic=True)

    doc.add_page_break()

    _heading(doc, "A.  The 50-hour floor", 2)

    _question(doc, "R1",
              "Does “not interested in any role of less than 50 hours” mean drop them, or just "
              "don’t chase the precision?",
              "Blocks four other answers",
              ["Your Q1 answer introduced a rule the model doesn’t currently have. 50 h is 3.05% "
               "of the nominal year, and it collides with two of your other answers:",
               "Q20 awards `Module Leader` at 2.5% = 41.05 h — below the floor. Q15 keeps "
               "`Research Mentor` at 2% = 32.84 h — below the floor. Applying the floor literally "
               "would also delete two roles that work correctly today: "
               "`Graduate School Board (Ordinary member)` (Pourya Shamsolmoali) and "
               "`Internally Distributed Funding panel reviewer` (Will Smith) — the second being "
               "one of the eight roles you originally asked about.",
               "Separately: does the floor apply to actual hours or to full-time-equivalent hours? "
               "At Claudio’s 0.4 FTE every 5% role is 32.8 h, so a floor on actual hours would "
               "strip nearly all admin from part-time staff."],
              "Recommended default",
              "Treat 50 h as a drafting guide for the spec, not a runtime filter: keep awarding "
              "everything that has a rate, and measure the floor against full-time-equivalent "
              "hours so part-time staff aren’t penalised. That keeps Q20 and Q15 intact.",
              "Drop below 50 h / keep awarding (default). And: FTE-scaled or full-time hours?",
              lines=4)

    _question(doc, "R2",
              "Where should the note about small roles appear in the individual reports, and "
              "what should it say?",
              "Wording needed",
              ["You asked for a note to that effect on all the individual reports. I need the "
               "wording, and whether it belongs in the report header (applying to the whole "
               "document) or at the foot of the Admin section (applying just to roles)."],
              "Recommended default",
              "Foot of the Admin section, reading: “Roles smaller than about 50 hours a year are "
              "not individually costed in this model.” Amend as you see fit.",
              "Wording / placement:", lines=3)

    doc.add_page_break()

    _heading(doc, "B.  Two answers that were cut short", 2)

    _question(doc, "R3", "Who are the research mentors?",
              "Answer truncated",
              ["The Q15 answer settled the unit — 2% per mentor, not per mentee — but the list "
               "ends after one name: “The current mentors are / Pengcheng”. I need the full list "
               "before mentoring can be costed.",
               "Also note this rate is 32.84 h, so R1 decides whether it survives at all."],
              "Needed from you",
              "The full list of current mentors. I’ll add them to WAW as `Research Mentor` rows.",
              "Mentors:", lines=4)

    _question(doc, "R4",
              "Is Claire Ingram the Deputy Director of Admissions (POVD), or something else?",
              "Ambiguous",
              ["Your Q13 answer — “There are other roles, e.g. Claire Ingram has one. It may not "
               "be obvious though they are part of the admissions team” — leaves the 10% POVD "
               "deputy unassigned.",
               "Claire Ingram currently appears in WAW as `Outreach and Recruitment Coordinator`, "
               "which maps to `Outreach and Extra-Curricular Activities` at 5%. So: is she the "
               "POVD deputy at 10% instead, does she hold both, or is the POVD deputy someone "
               "else? And who else counts as “part of the admissions team” beyond the four "
               "Academic Ambassadors already credited at 5% each?"],
              "Needed from you",
              "The POVD deputy’s name, plus anyone else in the admissions team who should be "
              "credited and at what rate.",
              "POVD deputy / others in the team:", lines=4)

    doc.add_page_break()

    _heading(doc, "C.  New — found while implementing your answers", 2)
    _para(doc,
          "Your Q26 answer said “I think we ignore SCSE modules from WTW”. That is true in "
          "effect, but not by design — and the mechanism does more damage than intended.",
          color=INK_SOFT)

    _question(doc, "R5",
              "SCSE modules are being dropped by a parsing bug, not a policy. Should they be "
              "parsed?",
              "Defect · removes 9 modules and 6 staff",
              ["In `WTW 2026-7.csv` the nine SCSE rows carry “-” in the semester column. The "
               "loader does `int(s.split(\"-\")[0])` on that, which raises, and the surrounding "
               "`except (IndexError, ValueError): continue` silently discards the whole row. "
               "FSSE, HRAS, RASS, SSAS, CASA, SESA, SCDR, REMS and HUFS never enter the model.",
               "The knock-on effect is larger than the missing teaching. The roster is built from "
               "whoever appears in WTW, so anyone whose only WTW appearance is an SCSE module "
               "disappears from the model completely — no workload document at all. That is the "
               "real reason Richard Hawkins is missing, and it explains Q21: every one of the four "
               "people in `Part time.csv` had been silently removed, which is why no one in the "
               "model had a part-time FTE.",
               "Fixing the parse is a two-line change. The question is what should happen next: "
               "should SCSE modules generate teaching hours like any other, or be excluded from "
               "teaching but still put their staff on the roster?"],
              "Recommended default",
              "Fix the parse, and treat SCSE modules as normal teaching. If they should stay "
              "uncosted, say so and I’ll exclude them explicitly — with a visible note — rather "
              "than by accident.",
              "Parse and cost normally (default) / parse but exclude from teaching:",
              lines=3,
              table=(["Staff member", "Only appears in WTW via", "In Part time.csv"],
                     [("Richard Hawkins", "CASA, FSSE, RASS, REMS, SCDR, SESA", "—"),
                      ("Sarah Carrington", "FSSE, SCDR, SSAS", "0.8 FTE"),
                      ("David Pumfrey", "HRAS, HUFS", "0.5 FTE"),
                      ("Mark Sujan", "CASA, HUFS", "0.8 FTE"),
                      ("Mark Nicholson", "RASS, SSAS", "— (0.8 per Q21)"),
                      ("Oleg Lisagor", "FSSE, HRAS, SSAS", "—")]))

    _question(doc, "R6",
              "Should staff with roles but no teaching be on the roster at all?",
              "Design decision · resolves Q7 vs Q26",
              ["Your two answers disagree about Richard Wilson: Q7 says “I thought Richard Wilson "
               "had a document”, Q26 groups him with “the others don’t need a workload model”.",
               "The cause is separate from R5. His only WTW row is the SAINTS AI module, which has "
               "no module code, so that row is skipped too — and with it, him. He is in "
               "`Part time.csv` at 0.6 FTE, is the ART staff rep, and is now a Research Group "
               "Leader after the Q6 restructure, but receives none of it.",
               "This is a rule question, not a name question. The specification says a member of "
               "staff not associated with any module simply has 0 teaching hours — it does not say "
               "they vanish. Today only the Head of Department is special-cased back in. Changing "
               "the roster rule from “appears in WTW” to “active staff” would also restore "
               "Philippa Ryan (EDI Chair) and, once R5 is fixed, keep everyone consistent.",
               "The same question covers the four SAINTS-only names — Ibrahim Habli, Jennifer "
               "Chubb, Phillip Morgan and Tom Stoneham. Are they CS staff who need documents, or "
               "external contributors who correctly sit outside the model?"],
              "Recommended default",
              "Change the rule to “active staff”, so anyone with a role, an FTE or a supervision "
              "load gets a document even with no teaching — as the spec already describes.",
              "Roster rule: active staff (default) / keep WTW-only. And: the four SAINTS names — "
              "in or out?", lines=4)

    doc.add_page_break()

    _heading(doc, "D.  Two small confirmations", 2)

    _question(doc, "R7",
              "Ethics Committee membership at 20% each is now live — 1,313.6 h across four people. "
              "Still right?",
              "Confirm scale",
              ["When you confirmed 20% for ordinary members in Q17, three of the four members were "
               "still being dropped by the blank-role bug, so only Dimitar Kazakov was affected. "
               "That bug is now fixed, so Farid Bello, Josh Levett and Yan Jia each receive 328.4 h "
               "as well.",
               "Yan Jia’s admin total is now 503.4 h. Flagging it because the number changed "
               "meaning after the fix, not to reopen the rate."],
              "Needed from you",
              "Confirm 20% each, or give a lower member rate now the full membership is counted.",
              "Confirm / revise:", lines=2)

    _question(doc, "R8",
              "Should the parser skip WAW rows whose holder reads “see main roles below”?",
              "Housekeeping",
              ["Seven rows are human-readable cross-references rather than assignments — "
               "`ex officio, Chair GSB`, `ex officio, REF lead`, `ex officio, REF impact lead`, "
               "`EDI rep`, `GSB PGR supervisor rep`, `PGR training officer`, "
               "`Disability representative`. They are useful to a person reading WAW, but once "
               "Q23 makes unknown role names raise a warning, each will produce a spurious one.",
               "Also, on Q19 you confirmed keeping the online exclusion but didn’t say whether the "
               "four online rows should be annotated in Appendix A. I’ll annotate them unless you "
               "say otherwise."],
              "Recommended default",
              "Yes — skip any row whose holder cell begins “see main roles”, leaving the rows in "
              "place for human readers.",
              "yes / no:", lines=2)

    _heading(doc, "Anything else", 2)
    _answer_box(doc, "Corrections or context not covered above:", lines=6)

    return doc


if __name__ == "__main__":
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    build().save(OUTPUT_PATH)
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
